//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25112023_WebformsVeritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int id { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public int KategoriID { get; set; }
        public int KullaniciID { get; set; }
        public bool Durum { get; set; }
        public bool Silindi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Resim { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
